version: "3.9"
services:
  api:
    build: ./apps/api
    env_file:
      - ./apps/api/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./apps/api:/app
  web:
    build: ./apps/web
    env_file:
      - ./apps/web/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./apps/web:/app
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: tracker
      POSTGRES_DB: tracker
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
